/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DefaultCard: typeof import('./src/components/DefaultCard.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VCallback: typeof import('./src/components/VCallback.vue')['default']
    VMarks: typeof import('./src/components/VMarks.vue')['default']
    VProfile: typeof import('./src/components/VProfile.vue')['default']
    VStatisticBlock: typeof import('./src/components/VStatisticBlock.vue')['default']
    VStatistics: typeof import('./src/components/VStatistics.vue')['default']
    VUniversities: typeof import('./src/components/VUniversities.vue')['default']
    WhyWe: typeof import('./src/components/WhyWe.vue')['default']
  }
}
